### ISSUE TITLE
List indexing

### ISSUE THREAD

**Issue by PaddyAlton** [chiphuyen/python-is-cool#1]
Hi! Super useful compilation - some of these took me _years_ to discover. I'll certainly be directing people here, so thanks for taking the time.

I believe there may be a small issue with the text in section 2.2, this bit:

> The syntax [x:y:z] means "take every zth element of a list from index x to index y", with 0 being the default value of x and -1 being the default value of y. When z is negative, it means going backwards. So if we want to take every 2th element of a list, we use [::2], which is the same as `[0:-1:2]`.

My understanding is that -1 isn't the default value of y, and `[::2]` is different to `[0:-1:2]`. Specifically, `[x:y]` means 'start at index x, stop _before_ index y'. The default value of y is kind-of -0 (although that would be bad syntax), and using `[:-1]` will drop the last element.

Concretely (I tried it with python 3.6):

```
k = [0, 1, 2, 3, 4, 5, 6, 7, 8] # odd number of elements
a = k[::2]    # a <- [0, 2, 4, 6, 8]
b = k[0:-1:2] # b <- [0, 2, 4, 6]
```

In the second case the indexing starts at 0, ends before 8, and strides by 2.

Hope this is a useful contribution!

**Comment by chiphuyen** [comment]
You're absolutely right I was being sloppy. Thank you!
