### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by gsk12** [chiphuyen/python-is-cool#2]
Thank you for this guide.

In section 5 I think: 

> If we intend that only **Endoer**, Decoder, and Loss are ever to be imported and used in another module, we should specify that in parts.py using the __all__ keyword.

was intended to be:

> If we intend that only **Encoder**, Decoder, and Loss are ever to be imported and used in another module, we should specify that in parts.py using the __all__ keyword.

**Comment by chiphuyen** [comment]
fixed. thanks!
